import {
  ApplicationConfig,
  inject,
  provideAppInitializer,
  provideBrowserGlobalErrorListeners,
} from '@angular/core';
import { provideRouter, withInMemoryScrolling } from '@angular/router';
import { provideAnimations } from '@angular/platform-browser/animations';
import {
  LucideArrowLeft,
  LucideArrowRight,
  LucideCamera,
  LucideChartNoAxesCombined,
  LucideCheck,
  LucideChevronDown,
  LucideChevronRight,
  LucideChevronLeft,
  LucideCircleCheck,
  LucideCircleDashed,
  LucideCircleHelp,
  LucideCloudUpload,
  LucideCrosshair,
  LucideEraser,
  LucideEye,
  LucideFileSpreadsheet,
  LucideFlame,
  LucideHand,
  LucideHouse,
  LucideImage,
  LucideImages,
  LucideLayers,
  LucideLoaderCircle,
  LucideLogOut,
  LucideMenu,
  LucidePause,
  LucidePersonStanding,
  LucidePlay,
  LucideRefreshCw,
  LucideRotateCcw,
  LucideScanSearch,
  LucideSettings,
  LucideShield,
  LucideShieldCheck,
  LucideSparkles,
  LucideStethoscope,
  LucideTarget,
  LucideThermometer,
  LucideTimeline,
  LucideTrash2,
  LucideTriangleAlert,
  LucideUserRound,
  LucideUsersRound,
  LucideWind,
  LucideWorkflow,
  LucideX,
  provideLucideIcons,
} from '@lucide/angular';

import { appRoutes } from './app.routes';
import { AuthService } from './core/auth/auth.service';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(
      appRoutes,
      withInMemoryScrolling({
        anchorScrolling: 'enabled',
        scrollPositionRestoration: 'enabled',
      }),
    ),
    provideAnimations(),
    // Eagerly instantiate AuthService so the session is resolved at startup.
    provideAppInitializer(() => {
      inject(AuthService);
    }),
    provideLucideIcons(
      LucideArrowLeft,
      LucideArrowRight,
      LucideCamera,
      LucideChartNoAxesCombined,
      LucideCheck,
      LucideChevronDown,
      LucideChevronRight,
      LucideChevronLeft,
      LucideCircleCheck,
      LucideCircleDashed,
      LucideCircleHelp,
      LucideCloudUpload,
      LucideCrosshair,
      LucideEraser,
      LucideEye,
      LucideFileSpreadsheet,
      LucideFlame,
      LucideHand,
      LucideHouse,
      LucideImage,
      LucideImages,
      LucideLayers,
      LucideLoaderCircle,
      LucideLogOut,
      LucideMenu,
      LucidePause,
      LucidePersonStanding,
      LucidePlay,
      LucideRefreshCw,
      LucideRotateCcw,
      LucideScanSearch,
      LucideSettings,
      LucideShield,
      LucideShieldCheck,
      LucideSparkles,
      LucideStethoscope,
      LucideTarget,
      LucideThermometer,
      LucideTimeline,
      LucideTrash2,
      LucideTriangleAlert,
      LucideUserRound,
      LucideUsersRound,
      LucideWind,
      LucideWorkflow,
      LucideX,
    ),
  ],
};
